version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_test
    ports:
      - "27018:27017" # 호스트의 27018 포트를 컨테이너의 27017 포트에 매핑
    volumes:
      - mongodb_data_test:/data/db # 별도의 볼륨 사용
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # 초기 root 사용자 이름
      - MONGO_INITDB_ROOT_PASSWORD=secret # 초기 root 비밀번호
      - MONGO_INITDB_DATABASE=admin # 초기 데이터베이스 이름 (선택 사항)

volumes:
  mongodb_data_test: # MongoDB 데이터를 저장할 별도의 볼륨 정의
